### ISSUE TITLE
Paged table rows are empty when scrolled into view

### ISSUE THREAD

**Issue by steveblamey** [uzerpllp/uzerp#236]
When viewing, say, the sales order list (Logistics > Sales Orders > Sales Orders); scrolling down in the table shows all rows. After switching to page 2 (or any other page) and scrolling down, the previously hidden rows are empty.

**This behaviour has been observed in Chrome 89.0.4389.90 on Windows 20H2 - build 19042.867.**

![image](https://user-images.githubusercontent.com/297376/112337115-8b5c8e00-8cb5-11eb-82a1-f30ee7839600.png)

**Comment by steveblamey** [comment]
The issue seems to be caused by CSS applied by uzERP to jQuery Tablescroll.
https://github.com/uzerpllp/uzerp/blob/ac2423fe0cb131481e302b0098c7e20ebd598068/assets/css/uzerp/screen.less#L941

The workaround is to place the following CSS in user/theme.css:

```CSS
/* Unset relative positioning applied to td elements*/
.datagrid td, .tablescroll_head td {
    position: unset;
}

/* Set the head and wrapper widths to 100% to avoid a horizontal scrollbar when paging
Currently, the widths are applied by JS to the elements in px units. Use !important to override.*/
.datagrid, .tablescroll_head, .datagrid, .tablescroll_wrapper {
    width: 100% !important;
}
```
